### ISSUE TITLE
Why use empty instead of is_null?

### ISSUE THREAD

**Issue by brunoti** [Waavi/Sanitizer#2]
I think that would be better to use is_null to verify if the input is "empty" on the applyField method.

Like this:

```php
    /**
     *  Apply the given filter by its name
     *  @param  $name
     *  @return Filter
     */
    protected function applyFilter($name, $value, $options = [])
    {
        // If the filter does not exist, throw an Exception:
        if (!isset($this->filters[$name])) {
            throw new InvalidArgumentException("No filter found by the name of $name");
        }
        // If the given value is null, skip the sanitizer
        if (is_null($value)) {
            return $value;
        }
        $filter = $this->filters[$name];
        if ($filter instanceof Closure) {
            return call_user_func_array($filter, [$value, $options]);
        } else {
            $filter = new $filter;
            return $filter->apply($value, $options);
        }
    }
```

I want use a filter that trim empty fields to null instead of leaving just an empty string.

If you accept it I can make a pull request with the feature. 

I really like the package and would be very nice to contribute with you guys! There are some features that you need some help to implement? I have some in mind...

**Comment by sildraug** [comment]
Hi Brunoti,

There is no point in sanitizing an empty string or array, and because the main purpose of the Sanitization library is to be used with input coming from HTML forms, no null values are expected (and therefore a null value check would be of little value).

I'm sorry but we can't make this change at this time, you are free to fork the project if you feel this is a mistake though.

Best!

**Comment by brunoti** [comment]
Thanks for the feedback! You are right. 

But what about the ideia of transform the empty string in null? Or casting numbers and booleans?

You think that this is not a job for the sanitizer?

**Comment by sildraug** [comment]
@brunoti we've implemented the changes you asked for. I just pushed v1.0.5 with no is_empty check and a new filter called 'cast'.

**Comment by brunoti** [comment]
Thanks @sildraug! Me and my coworkers are very happy to use this lib.

Cheers!

**Comment by plusz** [comment]
I think this error appeared again in version 1.0.11 :(

Example code generating issue (filter-text index not found - because sanitizer returns null)
It worked from 1.0.5 till 1.0.10

$cleaned = \Sanitizer::make($request->all(), ['filter-text' => 'trim|strip_tags'])->sanitize();
        }
$filterName = preg_replace('/[^a-zA-Z0 -]/u', ' ', $cleaned['filter-text']);
